[general]
giveJournal = true
holdToCast = true
doMinigame = true
showUnread = true
showToasts = true
minigameDifficulty = 1.0
rodDurabilityMultiplier = 1.0
defaultLineColor = false
hideUnknownFishNames = false
baseCrateRarity = 20
[worldgen]
disableFishingBoat = false
